### ISSUE TITLE
TODO: image url 

### ISSUE THREAD

**Issue by stevensona** [narrative/clubcast2-hs#1]
Regarding "TODO this field name may be wrong"
https://github.com/narrative/clubcast2-hs/blob/master/src/Clubcast.hs#L137

The url is stored in the href attribute of the "itunes:image" node.

**Comment by eriknstevenson** [comment]
Thanks for pointing that out, I will be get it fixed shortly.

**Comment by eriknstevenson** [comment]
Fixed in 2a7fc74 however I will leave this open because currently in cases where feeds do not provide this attribute on each episode, the image field in the output is being set to null. In the future it will be set to the image URL provided by the overall channel.

**Comment by stevensona** [comment]
That's what I do as well.

**Comment by eriknstevenson** [comment]
Should be falling back on the `itunes:image` node found in the overall feed file now.

**Comment by stevensona** [comment]
Just a heads up: Some of the episodes don't contain authors either. I noticed this late in testing.

**Comment by eriknstevenson** [comment]
Thanks
